version: '3.1'
services:
  front_end:
    container_name: cripto_front_end
    build: ./front_end
    volumes:
      - /front_end/node_modules
    ports:
      - '3100:3000'
    links:
      - "back_end:cripto_back_end"
  back_end:
    build: ./back_end
    container_name: cripto_back_end
    ports:
      - "8100:8000"
    links:
      - "postgres:cripto_postgres"
      - "redis:cripto_redis"
  postgres:
    container_name: cripto_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
        - ./back_end/migrations:/docker-entrypoint-initdb.d/
    ports:
      - "5100:5432"
  redis:
    container_name: cripto_redis
    image: redis:alpine